version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel_app
    volumes:
      - ./app:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT={DB_PORT}
      - MYSQL_DATABASE=${DB_DATABASE} 
      - MYSQL_USER=${DB_USERNAME} 
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "9000:9000"
    networks:
      - laravel
    command: >
      sh -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
             chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
             php-fpm"

  webserver:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel

  database:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE} 
      - MYSQL_USER=${DB_USERNAME} 
      - MYSQL_PASSWORD=${DB_PASSWORD}

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
